### ISSUE TITLE
Testimonials

### ISSUE THREAD

**Issue by spiltcoffee** [spiltcoffee/aciddotexe.github.io#7]
This is gonna be hilarious...

Add testimonials, like

> ⭐⭐⭐⭐⭐
> Good wife, 10/10, would marry again
- spiltcoffee

> ⭐⭐`
> *yelling*
- Willow, pet dog

Ask around for some more, flesh this out.

**Comment by Humble-Bumble-Bee** [comment]
> ⭐⭐⭐⭐⭐
> Life and loudspeaker of the party
* Humble-bumble-bee

**Comment by charlottepierce** [comment]
> 10/10 hugs, many warm ⭐️⭐️⭐️⭐️⭐️🎉

* charlemagne

**Comment by spiltcoffee** [comment]
@Humble-Bumble-Bee @charlottepierce updated https://aciddotexe.com/testimonials.html
do let me know if you want a different avatar or link to be used (or no link)

**Comment by charlottepierce** [comment]
> @Humble-Bumble-Bee @charlottepierce updated https://aciddotexe.com/testimonials.html do let me know if you want a different avatar or link to be used (or no link)

hmm I will go with no link

**Comment by spiltcoffee** [comment]
Actually, yeah, I'll just remove the links for now and see how it goes.

**Comment by spiltcoffee** [comment]
updated https://aciddotexe.com/testimonials.html, no links now

**Comment by Humble-Bumble-Bee** [comment]
![Jocelyn Pride Icon by Beaglescouts](https://user-images.githubusercontent.com/47409907/208829193-10b2507a-3d74-4a26-80a2-f789494ce8b9.png)
@spiltcoffee I'll go with this avatar.

**Comment by spiltcoffee** [comment]
@Humble-Bumble-Bee updated https://aciddotexe.com/testimonials.html with new avatar 👍

**Comment by FitzYordle** [comment]
![Spamton_screenshot_shop](https://user-images.githubusercontent.com/121164881/208885441-2e61ae73-91e1-4617-b53d-ad5fc98b76e8.png)
Top strimmer, would invite to wedding again  ⭐️⭐️⭐️⭐️⭐️

**Comment by spiltcoffee** [comment]
@FitzYordle added https://aciddotexe.com/testimonials.html

also:
- added a testimonial from ItsMeTonyG
- randomised the order of the testimonials
- added issue template for future testimonials
- typed and read the word testimonial so much it's losing meaning
